### ISSUE TITLE
Cuda not found after pulling docker image at  docker pull anibali/pytorch:1.4.0-cuda10.1

### ISSUE THREAD

**Issue by likwifi** [anibali/docker-pytorch#27]
I've run command  `docker pull anibali/pytorch:1.4.0-cuda10.1`
after connected to container with command  `docker run -it anibali/pytorch:1.4.0-cuda10.1 sh` 
both nvcc and nvidia-smi not found.

Output from my vm's nvidia-smi.

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
|   0  Tesla V100-PCIE...  Off  | 00000000:37:00.0 Off |                    0 |
| N/A   59C    P0    46W / 250W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:86:00.0 Off |                    0 |
| N/A   49C    P0    37W / 250W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by anibali** [comment]
Have you set up [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) and tested that it works? If it's set up correctly, you should be able to run the following and get proper nvidia-smi output:

```
$ docker run -it --gpus=all nvidia/cuda:10.1-base-ubuntu16.04 nvidia-smi
```

Note the inclusion of the  `--gpus=all` option in the docker run command---you may find that this is required or not depending on how you're set up.

If that doesn't work, then the problem is not specific to this project and you should make sure that you get nvidia-docker working properly first.

**Comment by likwifi** [comment]
--gpus=all fixed my problem thanks.
